name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: pypi-publish

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: 3.11
        cache: true

    - name: Install dependencies
      run: pdm install -v --dev

    - name: Run tests
      run: python -m pytest

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref }}
        tag_name: ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Build and publish to PyPI
      env:
        PDM_PUBLISH_USERNAME: ${{ secrets.PDM_PUBLISH_USERNAME }}
        PDM_PUBLISH_PASSWORD: ${{ secrets.PDM_PUBLISH_PASSWORD }}
      run: |
        pdm publish
